name: 'Textlint Action'
description: 'lint a document with textlint'
author: "yamamoto-febc"
branding:
  color: 'blue'
  icon: 'check'
inputs:
  working-directory:
    description: 'working directory'
    required: false
    default: '.'
runs:
  using: 'docker'
  image: 'docker://ghcr.io/sacloud/textlint-action:v0.0.2'
  args:
    - ${{ inputs.working-directory}}